@baseUrl = http://localhost:3000

@authToken = {{authenticate.response.body.accessToken}}

@id = fd5faca7-c758-4bbc-9ce1-a5a640cffbab
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###USERS GET ONE
GET {{baseUrl}}/users/{{id}}
Authorization: Bearer {{authToken}}

###USERS POST ONE 
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@email.com",
  "password": "password123"
}

###USERS PATCH ONE  
PATCH {{baseUrl}}/users/{{id}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Teste Atualizado",
  "coisaErrada": "coisaErrada"
}

###USERS DELETE ONE
DELETE {{baseUrl}}/users/{{id}}/
Authorization: Bearer {{authToken}}




###Auth POST ONE 
# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "password123"
}